# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='KeystrokeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('keystroke', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'keystroke_event',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='MouseClickEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('x_position', models.PositiveSmallIntegerField()),
                ('y_position', models.PositiveSmallIntegerField()),
                ('html_element', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mouse_click_event',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='MouseHoverEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('html_element', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mouse_hover_event',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='MouseMovementEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('start_x_position', models.PositiveSmallIntegerField()),
                ('start_y_position', models.PositiveSmallIntegerField()),
                ('start_html_element', models.TextField()),
                ('end_x_position', models.PositiveSmallIntegerField()),
                ('end_y_position', models.PositiveSmallIntegerField()),
                ('end_html_element', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mouse_movement_event',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='MouseScrollEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mouse_scroll_event',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='TextSelectionEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('selection', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'text_selection_event',
            },
            bases=('core.event',),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session'),
        ),
    ]
