# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160427_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PullRequest'),
        ),
    ]
