# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160512_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtype',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
