# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 18:34
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160519_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystrokeevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mouseclickevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mousepositionevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mousescrollevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='semanticevent',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='windowresolutionevent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='keystrokeevent',
            name='created_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AddField(
            model_name='mouseclickevent',
            name='created_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AddField(
            model_name='mousepositionevent',
            name='created_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AddField(
            model_name='mousescrollevent',
            name='created_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AddField(
            model_name='semanticevent',
            name='started_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AddField(
            model_name='windowresolutionevent',
            name='created_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
    ]
