# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160524_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_events', to='core.Session'),
        ),
    ]
