# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160524_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together=set([('repository', 'pull_request_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('owner', 'name', 'platform')]),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('pull_request', 'user')]),
        ),
    ]
