# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160530_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([]),
        ),
    ]
