# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 18:14
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160531_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTabEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('created_at', core.fields.UnixTimeStampField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session')),
            ],
            options={
                'db_table': 'active_tab_event',
            },
        ),
        migrations.RenameField(
            model_name='keystrokeevent',
            old_name='created_at',
            new_name='key_down_at',
        ),
        migrations.RenameField(
            model_name='semanticevent',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='semanticevent',
            name='duration',
        ),
        migrations.AddField(
            model_name='keystrokeevent',
            name='key_up_at',
            field=core.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='windowresolutionevent',
            table='window_resolution_event',
        ),
    ]
