# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 18:17
from __future__ import unicode_literals

import unixtimestampfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160531_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystrokeevent',
            name='key_down_at',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='keystrokeevent',
            name='key_up_at',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True),
        ),
    ]
