# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 18:39
from __future__ import unicode_literals

import unixtimestampfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160531_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTabEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session')),
            ],
            options={
                'db_table': 'change_tab_event',
            },
        ),
        migrations.RemoveField(
            model_name='activetabevent',
            name='session',
        ),
        migrations.DeleteModel(
            name='ActiveTabEvent',
        ),
    ]
