# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_htmlpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeystrokeType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'keystroke_type',
            },
        ),
        migrations.RemoveField(
            model_name='keystrokeevent',
            name='key_down_at',
        ),
        migrations.RemoveField(
            model_name='keystrokeevent',
            name='key_up_at',
        ),
        migrations.AddField(
            model_name='keystrokeevent',
            name='created_at',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AddField(
            model_name='keystrokeevent',
            name='keystroke_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.KeystrokeType'),
            preserve_default=False,
        ),
    ]
