# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160606_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Repository'),
        ),
    ]
