# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160614_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('commit_hash', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('line_number', models.PositiveIntegerField()),
                ('semantic_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.SemanticEvent')),
            ],
            options={
                'db_table': 'file_position',
            },
        ),
        migrations.RemoveField(
            model_name='eventposition',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventPosition',
        ),
    ]
