# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160616_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileposition',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
