# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160623_0747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username',)]),
        ),
    ]
